# Generated by Django 5.1.2 on 2025-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=10, unique=True)),
                ('destination', models.CharField(max_length=255)),
                ('route_length', models.FloatField()),
                ('first_bus_mon_sat', models.CharField(max_length=20)),
                ('first_bus_sunday', models.CharField(max_length=20)),
                ('last_bus_mon_sat', models.CharField(max_length=20)),
                ('last_bus_sunday', models.CharField(max_length=20)),
                ('journey_time', models.CharField(max_length=50)),
                ('frequency_mon_sat', models.CharField(max_length=50)),
                ('frequency_sunday', models.CharField(max_length=50)),
                ('fare', models.IntegerField()),
            ],
        ),
    ]
